export const BASE_SERVINGS = 4;

export const INGREDIENTS_BASE = [
  { id: "oil-base",    name: "Extra-virgin olive oil (for base)",                              amount: 60,   unit: "ml",    category: "Pantry" },
  { id: "oil-shell",   name: "Extra-virgin olive oil (for shellfish)",                         amount: 15,   unit: "ml",    category: "Pantry" },
  { id: "oil-drizzle", name: "Extra-virgin olive oil (for drizzling)",                         amount: 15,   unit: "ml",    category: "Pantry" },
  { id: "shrimp",      name: "Large shrimp (26-30/lb), peeled & deveined, shells reserved",   amount: 226,  unit: "g",     category: "Seafood" },
  { id: "onion",       name: "Yellow onion, ¼-inch dice",                                      amount: 0.5,  unit: "piece", category: "Produce" },
  { id: "fennel",      name: "Fennel bulb, ¼-inch dice (fronds reserved)",                    amount: 1,    unit: "piece", category: "Produce" },
  { id: "salt",        name: "Diamond Crystal kosher salt",                                    amount: 0.5,  unit: "tsp",   category: "Pantry" },
  { id: "garlic",      name: "Garlic cloves, minced",                                          amount: 4,    unit: "piece", category: "Produce" },
  { id: "oregano",     name: "Fresh oregano, minced",                                          amount: 2,    unit: "tsp",   category: "Produce" },
  { id: "pepper",      name: "Red pepper flakes",                                              amount: 0.25, unit: "tsp",   category: "Pantry" },
  { id: "wine",        name: "Dry white wine",                                                 amount: 240,  unit: "ml",    category: "Pantry" },
  { id: "saffron",     name: "Saffron",                                                        amount: 1,    unit: "pinch", category: "Pantry" },
  { id: "clam-juice",  name: "Clam juice (bottled)",                                           amount: 237,  unit: "ml",    category: "Seafood" },
  { id: "passata",     name: "Tomato passata",                                                 amount: 700,  unit: "g",     category: "Pantry" },
  { id: "squid",       name: "Squid, bodies in ½-inch rings, tentacles whole",                amount: 454,  unit: "g",     category: "Seafood" },
  { id: "cod",         name: "Skinless cod fillet (¾–1 inch thick), 2×1-inch pieces",        amount: 454,  unit: "g",     category: "Seafood" },
  { id: "clams",       name: "Littleneck clams, scrubbed & purged",                           amount: 454,  unit: "g",     category: "Seafood" },
  { id: "mussels",     name: "Mussels, scrubbed & debearded",                                 amount: 226,  unit: "g",     category: "Seafood" },
  { id: "parsley",     name: "Flat-leaf parsley, chopped",                                    amount: 0.25, unit: "cup",   category: "Produce" },
];

export const NIGHT_TRAD = [
  { title: "Purge the clams",       desc: "Submerge clams in salted cold water (~3% salinity — about 1 tbsp salt per 2 cups). Let stand 30 min. Lift out. If sand remains, drain, refill, and repeat until water runs clear. Refrigerate clams.",                                                                                                              timer: 1800, timerLabel: "30 min",   burner: "prep",   parallel: null },
  { title: "Prep the shrimp",       desc: "Peel and devein shrimp. Reserve shells in a small bowl for the base. Cover peeled shrimp and refrigerate.",                                                                                                                                                                                                         timer: null, timerLabel: null,       burner: "prep",   parallel: null },
  { title: "Prep the vegetables",   desc: "Dice onion and fennel bulb into ¼-inch pieces, reserving fennel fronds. Mince garlic and oregano. Store in airtight containers in the fridge.",                                                                                                                                                                     timer: null, timerLabel: null,       burner: "prep",   parallel: null },
  { title: "Prep squid & cod",      desc: "Slice squid bodies into ½-inch rings; leave tentacles whole. Pat dry. Cut cod into 2×1-inch pieces. Cover and refrigerate separately.",                                                                                                                                                                             timer: null, timerLabel: null,       burner: "prep",   parallel: null },
  { title: "Toast shrimp shells",   desc: "Heat olive oil (base) in a Dutch oven over medium-high until shimmering. Add reserved shrimp shells, cook stirring frequently until bright pink and browning. Remove with slotted spoon; discard.",                                                                                                                  timer: null, timerLabel: null,       burner: "main",   parallel: null },
  { title: "Sauté aromatics",       desc: "Add onion, fennel, and salt to pot. Cook, stirring occasionally, until softened and beginning to brown (7–9 min). Stir in garlic, oregano, and red pepper flakes until fragrant (~1 min).",                                                                                                                         timer: 540,  timerLabel: "~9 min",   burner: "main",   parallel: null },
  { title: "Deglaze with wine & saffron", desc: "Stir in ¾ of the wine (180 ml) and saffron. Cook until reduced by about half.",                                                                                                                                                                                                                              timer: 300,  timerLabel: "~5 min",   burner: "main",   parallel: null },
  { title: "Build & reduce the broth",    desc: "Stir in clam juice and passata. Simmer, stirring occasionally, until reduced by about half.",                                                                                                                                                                                                                timer: 1050, timerLabel: "15–20 min", burner: "main",   parallel: null },
  { title: "Cool & refrigerate",    desc: "Remove from heat, cool to room temperature. Transfer to an airtight container and refrigerate overnight. You're done for tonight.",                                                                                                                                                                                   timer: null, timerLabel: null,       burner: "prep",   parallel: null },
];

export const DAY_TRAD = [
  { title: "Reheat the base",       desc: "Transfer tomato base back into your Dutch oven. Reheat over medium heat, stirring occasionally, until it reaches a gentle simmer.",                                                                                                                                                                                  timer: null, timerLabel: null,       burner: "main",   parallel: null },
  { title: "Prep the mussels",      desc: "Scrub mussels and pull off any beards. Discard any that are cracked or won't close when tapped.",                                                                                                                                                                                                                   timer: null, timerLabel: null,       burner: "prep",   parallel: null },
  { title: "Simmer the squid",      desc: "Reduce heat to low. Nestle squid into the simmering broth, cover, and gently simmer for 15 minutes.",                                                                                                                                                                                                              timer: 900,  timerLabel: "15 min",   burner: "main",   parallel: null },
  { title: "Add the cod",           desc: "Nestle cod pieces into the broth, cover, and gently simmer until just cooked through.",                                                                                                                                                                                                                             timer: 390,  timerLabel: "5–8 min",  burner: "main",   parallel: null },
  { title: "Add the shrimp",        desc: "Add shrimp, submerging in liquid. Cover and cook until pink and cooked through. Remove pot from heat. Start clams on 2nd burner now.",                                                                                                                                                                              timer: 180,  timerLabel: "2–4 min",  burner: "main",   parallel: "start" },
  { title: "Steam the clams",       desc: "AT THE SAME TIME: In a 12-inch skillet, combine clams, remaining ¼ cup wine, and 1 tbsp olive oil. Cover, boil over high heat. Transfer opened clams to pot.",                                                                                                                                                     timer: 390,  timerLabel: "5–8 min",  burner: "skillet",parallel: "with-prev" },
  { title: "Steam the mussels",     desc: "In same skillet with remaining liquid, add mussels. Cover, high heat until opened. Transfer with ~½ cup broth to pot.",                                                                                                                                                                                            timer: 180,  timerLabel: "2–4 min",  burner: "skillet",parallel: "end" },
  { title: "Finish & serve",        desc: "Return stew to a gentle simmer. Stir in parsley, season with salt and pepper. Divide among warmed bowls, ladle broth over, drizzle olive oil, garnish with fennel fronds. Serve with crusty bread or linguine.",                                                                                                    timer: null, timerLabel: null,       burner: "main",   parallel: null },
];

export const NIGHT_SV = [
  { title: "Purge the clams",           desc: "Submerge clams in salted cold water (~3% salinity). Let stand 30 min. If sand remains, repeat. Refrigerate clams.",                                                                                                                                                                                                 timer: 1800, timerLabel: "30 min",   burner: "prep",   parallel: null },
  { title: "Prep the shrimp",           desc: "Peel and devein shrimp. Reserve shells for the base. Season shrimp with a pinch of salt and a drizzle of olive oil, vacuum seal or zip-lock (water displacement method). Refrigerate the bag — you'll sous vide these tomorrow.",                                                                                    timer: null, timerLabel: null,       burner: "prep",   parallel: null },
  { title: "Prep the vegetables",       desc: "Dice onion and fennel into ¼-inch pieces (reserve fronds). Mince garlic and oregano. Refrigerate in containers.",                                                                                                                                                                                                  timer: null, timerLabel: null,       burner: "prep",   parallel: null },
  { title: "Prep squid & cod",          desc: "Slice squid bodies into ½-inch rings, tentacles whole. Season with a pinch of salt and olive oil, seal in a bag. Cut cod into 2×1-inch pieces, season with salt and olive oil, and optionally add a small sprig of thyme and a thin sliver of garlic to the bag. Seal in a separate bag.",                         timer: null, timerLabel: null,       burner: "prep",   parallel: null },
  { title: "Start sous vide for squid", desc: "Fill and start your sous vide bath at 138°F / 59°C. Once at temp, add the squid bag. This will cook while you build the broth — the squid needs 1–2 hours for silky-tender results.",                                                                                                                           timer: null, timerLabel: null,       burner: "sv",     parallel: "sv-start" },
  { title: "Toast shrimp shells",       desc: "While bath heats: heat olive oil (base) in a Dutch oven over medium-high. Add shells, cook until pink and browning. Remove and discard.",                                                                                                                                                                            timer: null, timerLabel: null,       burner: "main",   parallel: null },
  { title: "Sauté aromatics",           desc: "Add onion, fennel, and salt. Cook until softened and browning (7–9 min). Stir in garlic, oregano, red pepper flakes until fragrant (~1 min).",                                                                                                                                                                      timer: 540,  timerLabel: "~9 min",   burner: "main",   parallel: null },
  { title: "Deglaze with wine & saffron", desc: "Stir in ¾ of the wine (180 ml) and saffron. Cook until reduced by about half.",                                                                                                                                                                                                                              timer: 300,  timerLabel: "~5 min",   burner: "main",   parallel: null },
  { title: "Build & reduce the broth",  desc: "Stir in clam juice and passata. Simmer until reduced by about half. The squid is still cooking in the bath — no action needed there.",                                                                                                                                                                       timer: 1050, timerLabel: "15–20 min", burner: "main",   parallel: null },
  { title: "Remove squid, cool everything", desc: "Pull the squid bag from the bath (it should have at least 1 hr by now). Transfer bag to an ice bath to chill rapidly. Cool the broth to room temp. Refrigerate both the squid (in bag) and broth overnight.",                                                                                               timer: null, timerLabel: null,       burner: "sv",     parallel: "sv-end" },
];

export const DAY_SV = [
  { title: "Start sous vide for cod",   desc: "Fill and start your sous vide bath at 135°F / 57°C. Once at temp, add the cod bag. Set a 30-minute timer.",                                                                                                                                                                                                     timer: 1800, timerLabel: "30 min",   burner: "sv",     parallel: "sv-start" },
  { title: "Reheat the base",           desc: "While cod cooks: transfer the tomato base to your Dutch oven. Reheat over medium heat to a gentle simmer.",                                                                                                                                                                                                     timer: null, timerLabel: null,       burner: "main",   parallel: null },
  { title: "Prep the mussels",          desc: "Scrub mussels and remove beards. Discard any that won't close when tapped.",                                                                                                                                                                                                                                    timer: null, timerLabel: null,       burner: "prep",   parallel: null },
  { title: "Add shrimp to bath",        desc: "After cod has been in for 10 min, add the shrimp bag to the same bath. Both will finish together — cod gets 30 min total, shrimp gets 20 min. 135°F works beautifully for both.",                                                                                                                               timer: 1200, timerLabel: "20 min",   burner: "sv",     parallel: null },
  { title: "Remove proteins from bath", desc: "Pull both bags from the bath. Cut open and gently slide the cod and shrimp into the simmering broth. Add the pre-cooked squid (from the fridge bag) too. Let everything warm through gently for 2–3 minutes — do NOT boil.",                                                                                  timer: 150,  timerLabel: "2–3 min",  burner: "main",   parallel: "start" },
  { title: "Steam the clams",           desc: "AT THE SAME TIME: In a 12-inch skillet, combine clams, remaining ¼ cup wine, and 1 tbsp olive oil. Cover, boil over high heat. Transfer opened clams to pot.",                                                                                                                                                  timer: 390,  timerLabel: "5–8 min",  burner: "skillet",parallel: "with-prev" },
  { title: "Steam the mussels",         desc: "In same skillet with remaining liquid, add mussels. Cover, high heat until opened. Transfer with ~½ cup broth to pot.",                                                                                                                                                                                        timer: 180,  timerLabel: "2–4 min",  burner: "skillet",parallel: "end" },
  { title: "Finish & serve",            desc: "Return stew to a gentle simmer. Stir in parsley, season with salt and pepper. Divide among warmed bowls, ladle broth over, drizzle olive oil, garnish with fennel fronds. Serve with crusty bread or linguine.",                                                                                                timer: null, timerLabel: null,       burner: "main",   parallel: null },
];
